/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: shuffleInfo.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "shuffleInfo.pb-c.h"
void   shuffle_info__reorder_info__binary_info__init
                     (ShuffleInfo__ReorderInfo__BinaryInfo         *message)
{
  static const ShuffleInfo__ReorderInfo__BinaryInfo init_value = SHUFFLE_INFO__REORDER_INFO__BINARY_INFO__INIT;
  *message = init_value;
}
void   shuffle_info__reorder_info__layout_info__init
                     (ShuffleInfo__ReorderInfo__LayoutInfo         *message)
{
  static const ShuffleInfo__ReorderInfo__LayoutInfo init_value = SHUFFLE_INFO__REORDER_INFO__LAYOUT_INFO__INIT;
  *message = init_value;
}
void   shuffle_info__reorder_info__fixup_info__fixup_tuple__init
                     (ShuffleInfo__ReorderInfo__FixupInfo__FixupTuple         *message)
{
  static const ShuffleInfo__ReorderInfo__FixupInfo__FixupTuple init_value = SHUFFLE_INFO__REORDER_INFO__FIXUP_INFO__FIXUP_TUPLE__INIT;
  *message = init_value;
}
void   shuffle_info__reorder_info__fixup_info__init
                     (ShuffleInfo__ReorderInfo__FixupInfo         *message)
{
  static const ShuffleInfo__ReorderInfo__FixupInfo init_value = SHUFFLE_INFO__REORDER_INFO__FIXUP_INFO__INIT;
  *message = init_value;
}
void   shuffle_info__reorder_info__ccrlimitation__init
                     (ShuffleInfo__ReorderInfo__CCRLimitation         *message)
{
  static const ShuffleInfo__ReorderInfo__CCRLimitation init_value = SHUFFLE_INFO__REORDER_INFO__CCRLIMITATION__INIT;
  *message = init_value;
}
void   shuffle_info__reorder_info__init
                     (ShuffleInfo__ReorderInfo         *message)
{
  static const ShuffleInfo__ReorderInfo init_value = SHUFFLE_INFO__REORDER_INFO__INIT;
  *message = init_value;
}
size_t shuffle_info__reorder_info__get_packed_size
                     (const ShuffleInfo__ReorderInfo *message)
{
  assert(message->base.descriptor == &shuffle_info__reorder_info__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t shuffle_info__reorder_info__pack
                     (const ShuffleInfo__ReorderInfo *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &shuffle_info__reorder_info__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t shuffle_info__reorder_info__pack_to_buffer
                     (const ShuffleInfo__ReorderInfo *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &shuffle_info__reorder_info__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ShuffleInfo__ReorderInfo *
       shuffle_info__reorder_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ShuffleInfo__ReorderInfo *)
     protobuf_c_message_unpack (&shuffle_info__reorder_info__descriptor,
                                allocator, len, data);
}
void   shuffle_info__reorder_info__free_unpacked
                     (ShuffleInfo__ReorderInfo *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &shuffle_info__reorder_info__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   shuffle_info__metadata__inst_info__init
                     (ShuffleInfo__Metadata__InstInfo         *message)
{
  static const ShuffleInfo__Metadata__InstInfo init_value = SHUFFLE_INFO__METADATA__INST_INFO__INIT;
  *message = init_value;
}
void   shuffle_info__metadata__fun_info__init
                     (ShuffleInfo__Metadata__FunInfo         *message)
{
  static const ShuffleInfo__Metadata__FunInfo init_value = SHUFFLE_INFO__METADATA__FUN_INFO__INIT;
  *message = init_value;
}
void   shuffle_info__metadata__fixup_info__init
                     (ShuffleInfo__Metadata__FixupInfo         *message)
{
  static const ShuffleInfo__Metadata__FixupInfo init_value = SHUFFLE_INFO__METADATA__FIXUP_INFO__INIT;
  *message = init_value;
}
void   shuffle_info__metadata__gold_info__init
                     (ShuffleInfo__Metadata__GoldInfo         *message)
{
  static const ShuffleInfo__Metadata__GoldInfo init_value = SHUFFLE_INFO__METADATA__GOLD_INFO__INIT;
  *message = init_value;
}
void   shuffle_info__metadata__init
                     (ShuffleInfo__Metadata         *message)
{
  static const ShuffleInfo__Metadata init_value = SHUFFLE_INFO__METADATA__INIT;
  *message = init_value;
}
size_t shuffle_info__metadata__get_packed_size
                     (const ShuffleInfo__Metadata *message)
{
  assert(message->base.descriptor == &shuffle_info__metadata__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t shuffle_info__metadata__pack
                     (const ShuffleInfo__Metadata *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &shuffle_info__metadata__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t shuffle_info__metadata__pack_to_buffer
                     (const ShuffleInfo__Metadata *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &shuffle_info__metadata__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ShuffleInfo__Metadata *
       shuffle_info__metadata__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ShuffleInfo__Metadata *)
     protobuf_c_message_unpack (&shuffle_info__metadata__descriptor,
                                allocator, len, data);
}
void   shuffle_info__metadata__free_unpacked
                     (ShuffleInfo__Metadata *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &shuffle_info__metadata__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor shuffle_info__reorder_info__binary_info__field_descriptors[1] =
{
  {
    "rand_obj_offset",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(ShuffleInfo__ReorderInfo__BinaryInfo, has_rand_obj_offset),
    offsetof(ShuffleInfo__ReorderInfo__BinaryInfo, rand_obj_offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned shuffle_info__reorder_info__binary_info__field_indices_by_name[] = {
  0,   /* field[0] = rand_obj_offset */
};
static const ProtobufCIntRange shuffle_info__reorder_info__binary_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor shuffle_info__reorder_info__binary_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ShuffleInfo.ReorderInfo.BinaryInfo",
  "BinaryInfo",
  "ShuffleInfo__ReorderInfo__BinaryInfo",
  "ShuffleInfo",
  sizeof(ShuffleInfo__ReorderInfo__BinaryInfo),
  1,
  shuffle_info__reorder_info__binary_info__field_descriptors,
  shuffle_info__reorder_info__binary_info__field_indices_by_name,
  1,  shuffle_info__reorder_info__binary_info__number_ranges,
  (ProtobufCMessageInit) shuffle_info__reorder_info__binary_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor shuffle_info__reorder_info__layout_info__field_descriptors[6] =
{
  {
    "bb_size",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ShuffleInfo__ReorderInfo__LayoutInfo, has_bb_size),
    offsetof(ShuffleInfo__ReorderInfo__LayoutInfo, bb_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ShuffleInfo__ReorderInfo__LayoutInfo, has_type),
    offsetof(ShuffleInfo__ReorderInfo__LayoutInfo, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bb_fallthrough",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(ShuffleInfo__ReorderInfo__LayoutInfo, has_bb_fallthrough),
    offsetof(ShuffleInfo__ReorderInfo__LayoutInfo, bb_fallthrough),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "section",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ShuffleInfo__ReorderInfo__LayoutInfo, has_section),
    offsetof(ShuffleInfo__ReorderInfo__LayoutInfo, section),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "src_type",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ShuffleInfo__ReorderInfo__LayoutInfo, has_src_type),
    offsetof(ShuffleInfo__ReorderInfo__LayoutInfo, src_type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "info",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ShuffleInfo__ReorderInfo__LayoutInfo, info),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned shuffle_info__reorder_info__layout_info__field_indices_by_name[] = {
  2,   /* field[2] = bb_fallthrough */
  0,   /* field[0] = bb_size */
  5,   /* field[5] = info */
  3,   /* field[3] = section */
  4,   /* field[4] = src_type */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange shuffle_info__reorder_info__layout_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor shuffle_info__reorder_info__layout_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ShuffleInfo.ReorderInfo.LayoutInfo",
  "LayoutInfo",
  "ShuffleInfo__ReorderInfo__LayoutInfo",
  "ShuffleInfo",
  sizeof(ShuffleInfo__ReorderInfo__LayoutInfo),
  6,
  shuffle_info__reorder_info__layout_info__field_descriptors,
  shuffle_info__reorder_info__layout_info__field_indices_by_name,
  1,  shuffle_info__reorder_info__layout_info__number_ranges,
  (ProtobufCMessageInit) shuffle_info__reorder_info__layout_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor shuffle_info__reorder_info__fixup_info__fixup_tuple__field_descriptors[10] =
{
  {
    "offset",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo__FixupTuple, has_offset),
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo__FixupTuple, offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo__FixupTuple, has_type),
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo__FixupTuple, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "base_bbl_sym",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo__FixupTuple, has_base_bbl_sym),
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo__FixupTuple, base_bbl_sym),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "base_section",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo__FixupTuple, has_base_section),
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo__FixupTuple, base_section),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "target_bbl_sym",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo__FixupTuple, has_target_bbl_sym),
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo__FixupTuple, target_bbl_sym),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "target_section",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo__FixupTuple, has_target_section),
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo__FixupTuple, target_section),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "section",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo__FixupTuple, has_section),
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo__FixupTuple, section),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "add",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo__FixupTuple, has_add),
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo__FixupTuple, add),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "step",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo__FixupTuple, has_step),
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo__FixupTuple, step),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "info",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo__FixupTuple, info),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned shuffle_info__reorder_info__fixup_info__fixup_tuple__field_indices_by_name[] = {
  7,   /* field[7] = add */
  2,   /* field[2] = base_bbl_sym */
  3,   /* field[3] = base_section */
  9,   /* field[9] = info */
  0,   /* field[0] = offset */
  6,   /* field[6] = section */
  8,   /* field[8] = step */
  4,   /* field[4] = target_bbl_sym */
  5,   /* field[5] = target_section */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange shuffle_info__reorder_info__fixup_info__fixup_tuple__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor shuffle_info__reorder_info__fixup_info__fixup_tuple__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ShuffleInfo.ReorderInfo.FixupInfo.FixupTuple",
  "FixupTuple",
  "ShuffleInfo__ReorderInfo__FixupInfo__FixupTuple",
  "ShuffleInfo",
  sizeof(ShuffleInfo__ReorderInfo__FixupInfo__FixupTuple),
  10,
  shuffle_info__reorder_info__fixup_info__fixup_tuple__field_descriptors,
  shuffle_info__reorder_info__fixup_info__fixup_tuple__field_indices_by_name,
  1,  shuffle_info__reorder_info__fixup_info__fixup_tuple__number_ranges,
  (ProtobufCMessageInit) shuffle_info__reorder_info__fixup_info__fixup_tuple__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor shuffle_info__reorder_info__fixup_info__field_descriptors[8] =
{
  {
    "text",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo, n_text),
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo, text),
    &shuffle_info__reorder_info__fixup_info__fixup_tuple__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rodata",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo, n_rodata),
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo, rodata),
    &shuffle_info__reorder_info__fixup_info__fixup_tuple__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo, n_data),
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo, data),
    &shuffle_info__reorder_info__fixup_info__fixup_tuple__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "datarel",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo, n_datarel),
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo, datarel),
    &shuffle_info__reorder_info__fixup_info__fixup_tuple__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "initarray",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo, n_initarray),
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo, initarray),
    &shuffle_info__reorder_info__fixup_info__fixup_tuple__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "got",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo, n_got),
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo, got),
    &shuffle_info__reorder_info__fixup_info__fixup_tuple__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "init",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo, n_init),
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo, init),
    &shuffle_info__reorder_info__fixup_info__fixup_tuple__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fini",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo, n_fini),
    offsetof(ShuffleInfo__ReorderInfo__FixupInfo, fini),
    &shuffle_info__reorder_info__fixup_info__fixup_tuple__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned shuffle_info__reorder_info__fixup_info__field_indices_by_name[] = {
  2,   /* field[2] = data */
  3,   /* field[3] = datarel */
  7,   /* field[7] = fini */
  5,   /* field[5] = got */
  6,   /* field[6] = init */
  4,   /* field[4] = initarray */
  1,   /* field[1] = rodata */
  0,   /* field[0] = text */
};
static const ProtobufCIntRange shuffle_info__reorder_info__fixup_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor shuffle_info__reorder_info__fixup_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ShuffleInfo.ReorderInfo.FixupInfo",
  "FixupInfo",
  "ShuffleInfo__ReorderInfo__FixupInfo",
  "ShuffleInfo",
  sizeof(ShuffleInfo__ReorderInfo__FixupInfo),
  8,
  shuffle_info__reorder_info__fixup_info__field_descriptors,
  shuffle_info__reorder_info__fixup_info__field_indices_by_name,
  1,  shuffle_info__reorder_info__fixup_info__number_ranges,
  (ProtobufCMessageInit) shuffle_info__reorder_info__fixup_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor shuffle_info__reorder_info__ccrlimitation__field_descriptors[12] =
{
  {
    "all_obj",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(ShuffleInfo__ReorderInfo__CCRLimitation, has_all_obj),
    offsetof(ShuffleInfo__ReorderInfo__CCRLimitation, all_obj),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hybrid_obj",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(ShuffleInfo__ReorderInfo__CCRLimitation, has_hybrid_obj),
    offsetof(ShuffleInfo__ReorderInfo__CCRLimitation, hybrid_obj),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "static_got",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(ShuffleInfo__ReorderInfo__CCRLimitation, has_static_got),
    offsetof(ShuffleInfo__ReorderInfo__CCRLimitation, static_got),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "silicon_errata",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(ShuffleInfo__ReorderInfo__CCRLimitation, has_silicon_errata),
    offsetof(ShuffleInfo__ReorderInfo__CCRLimitation, silicon_errata),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tls_opt",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(ShuffleInfo__ReorderInfo__CCRLimitation, has_tls_opt),
    offsetof(ShuffleInfo__ReorderInfo__CCRLimitation, tls_opt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "got_opt",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(ShuffleInfo__ReorderInfo__CCRLimitation, has_got_opt),
    offsetof(ShuffleInfo__ReorderInfo__CCRLimitation, got_opt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "got_target",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(ShuffleInfo__ReorderInfo__CCRLimitation, has_got_target),
    offsetof(ShuffleInfo__ReorderInfo__CCRLimitation, got_target),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tls_got_target",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(ShuffleInfo__ReorderInfo__CCRLimitation, has_tls_got_target),
    offsetof(ShuffleInfo__ReorderInfo__CCRLimitation, tls_got_target),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "plt_target",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(ShuffleInfo__ReorderInfo__CCRLimitation, has_plt_target),
    offsetof(ShuffleInfo__ReorderInfo__CCRLimitation, plt_target),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "merged_target",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(ShuffleInfo__ReorderInfo__CCRLimitation, has_merged_target),
    offsetof(ShuffleInfo__ReorderInfo__CCRLimitation, merged_target),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ifunc_target",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(ShuffleInfo__ReorderInfo__CCRLimitation, has_ifunc_target),
    offsetof(ShuffleInfo__ReorderInfo__CCRLimitation, ifunc_target),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "missrandfile",
    12,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(ShuffleInfo__ReorderInfo__CCRLimitation, n_missrandfile),
    offsetof(ShuffleInfo__ReorderInfo__CCRLimitation, missrandfile),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned shuffle_info__reorder_info__ccrlimitation__field_indices_by_name[] = {
  0,   /* field[0] = all_obj */
  5,   /* field[5] = got_opt */
  6,   /* field[6] = got_target */
  1,   /* field[1] = hybrid_obj */
  10,   /* field[10] = ifunc_target */
  9,   /* field[9] = merged_target */
  11,   /* field[11] = missrandfile */
  8,   /* field[8] = plt_target */
  3,   /* field[3] = silicon_errata */
  2,   /* field[2] = static_got */
  7,   /* field[7] = tls_got_target */
  4,   /* field[4] = tls_opt */
};
static const ProtobufCIntRange shuffle_info__reorder_info__ccrlimitation__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 12 }
};
const ProtobufCMessageDescriptor shuffle_info__reorder_info__ccrlimitation__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ShuffleInfo.ReorderInfo.CCRLimitation",
  "CCRLimitation",
  "ShuffleInfo__ReorderInfo__CCRLimitation",
  "ShuffleInfo",
  sizeof(ShuffleInfo__ReorderInfo__CCRLimitation),
  12,
  shuffle_info__reorder_info__ccrlimitation__field_descriptors,
  shuffle_info__reorder_info__ccrlimitation__field_indices_by_name,
  1,  shuffle_info__reorder_info__ccrlimitation__number_ranges,
  (ProtobufCMessageInit) shuffle_info__reorder_info__ccrlimitation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor shuffle_info__reorder_info__field_descriptors[4] =
{
  {
    "bin",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ShuffleInfo__ReorderInfo, bin),
    &shuffle_info__reorder_info__binary_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "layout",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ShuffleInfo__ReorderInfo, n_layout),
    offsetof(ShuffleInfo__ReorderInfo, layout),
    &shuffle_info__reorder_info__layout_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fixup",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ShuffleInfo__ReorderInfo, n_fixup),
    offsetof(ShuffleInfo__ReorderInfo, fixup),
    &shuffle_info__reorder_info__fixup_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ccr_limitation",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ShuffleInfo__ReorderInfo, ccr_limitation),
    &shuffle_info__reorder_info__ccrlimitation__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned shuffle_info__reorder_info__field_indices_by_name[] = {
  0,   /* field[0] = bin */
  3,   /* field[3] = ccr_limitation */
  2,   /* field[2] = fixup */
  1,   /* field[1] = layout */
};
static const ProtobufCIntRange shuffle_info__reorder_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor shuffle_info__reorder_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ShuffleInfo.ReorderInfo",
  "ReorderInfo",
  "ShuffleInfo__ReorderInfo",
  "ShuffleInfo",
  sizeof(ShuffleInfo__ReorderInfo),
  4,
  shuffle_info__reorder_info__field_descriptors,
  shuffle_info__reorder_info__field_indices_by_name,
  1,  shuffle_info__reorder_info__number_ranges,
  (ProtobufCMessageInit) shuffle_info__reorder_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor shuffle_info__metadata__inst_info__field_descriptors[2] =
{
  {
    "offset",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ShuffleInfo__Metadata__InstInfo, offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ShuffleInfo__Metadata__InstInfo, size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned shuffle_info__metadata__inst_info__field_indices_by_name[] = {
  0,   /* field[0] = offset */
  1,   /* field[1] = size */
};
static const ProtobufCIntRange shuffle_info__metadata__inst_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor shuffle_info__metadata__inst_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ShuffleInfo.Metadata.InstInfo",
  "InstInfo",
  "ShuffleInfo__Metadata__InstInfo",
  "ShuffleInfo",
  sizeof(ShuffleInfo__Metadata__InstInfo),
  2,
  shuffle_info__metadata__inst_info__field_descriptors,
  shuffle_info__metadata__inst_info__field_indices_by_name,
  1,  shuffle_info__metadata__inst_info__number_ranges,
  (ProtobufCMessageInit) shuffle_info__metadata__inst_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor shuffle_info__metadata__fun_info__field_descriptors[4] =
{
  {
    "section",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ShuffleInfo__Metadata__FunInfo, section),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "offset",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ShuffleInfo__Metadata__FunInfo, offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "insts",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ShuffleInfo__Metadata__FunInfo, n_insts),
    offsetof(ShuffleInfo__Metadata__FunInfo, insts),
    &shuffle_info__metadata__inst_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "info",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ShuffleInfo__Metadata__FunInfo, info),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned shuffle_info__metadata__fun_info__field_indices_by_name[] = {
  3,   /* field[3] = info */
  2,   /* field[2] = insts */
  1,   /* field[1] = offset */
  0,   /* field[0] = section */
};
static const ProtobufCIntRange shuffle_info__metadata__fun_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor shuffle_info__metadata__fun_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ShuffleInfo.Metadata.FunInfo",
  "FunInfo",
  "ShuffleInfo__Metadata__FunInfo",
  "ShuffleInfo",
  sizeof(ShuffleInfo__Metadata__FunInfo),
  4,
  shuffle_info__metadata__fun_info__field_descriptors,
  shuffle_info__metadata__fun_info__field_indices_by_name,
  1,  shuffle_info__metadata__fun_info__number_ranges,
  (ProtobufCMessageInit) shuffle_info__metadata__fun_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor shuffle_info__metadata__fixup_info__field_descriptors[10] =
{
  {
    "offset",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ShuffleInfo__Metadata__FixupInfo, offset),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "section",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ShuffleInfo__Metadata__FixupInfo, section),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ShuffleInfo__Metadata__FixupInfo, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "base_bbl_sym",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ShuffleInfo__Metadata__FixupInfo, base_bbl_sym),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "base_section",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ShuffleInfo__Metadata__FixupInfo, base_section),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "target_bbl_sym",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(ShuffleInfo__Metadata__FixupInfo, target_bbl_sym),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "target_section",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(ShuffleInfo__Metadata__FixupInfo, target_section),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "add",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(ShuffleInfo__Metadata__FixupInfo, has_add),
    offsetof(ShuffleInfo__Metadata__FixupInfo, add),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "step",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(ShuffleInfo__Metadata__FixupInfo, has_step),
    offsetof(ShuffleInfo__Metadata__FixupInfo, step),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "info",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ShuffleInfo__Metadata__FixupInfo, info),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned shuffle_info__metadata__fixup_info__field_indices_by_name[] = {
  7,   /* field[7] = add */
  3,   /* field[3] = base_bbl_sym */
  4,   /* field[4] = base_section */
  9,   /* field[9] = info */
  0,   /* field[0] = offset */
  1,   /* field[1] = section */
  8,   /* field[8] = step */
  5,   /* field[5] = target_bbl_sym */
  6,   /* field[6] = target_section */
  2,   /* field[2] = type */
};
static const ProtobufCIntRange shuffle_info__metadata__fixup_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor shuffle_info__metadata__fixup_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ShuffleInfo.Metadata.FixupInfo",
  "FixupInfo",
  "ShuffleInfo__Metadata__FixupInfo",
  "ShuffleInfo",
  sizeof(ShuffleInfo__Metadata__FixupInfo),
  10,
  shuffle_info__metadata__fixup_info__field_descriptors,
  shuffle_info__metadata__fixup_info__field_indices_by_name,
  1,  shuffle_info__metadata__fixup_info__number_ranges,
  (ProtobufCMessageInit) shuffle_info__metadata__fixup_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor shuffle_info__metadata__gold_info__field_descriptors[13] =
{
  {
    "all_obj",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(ShuffleInfo__Metadata__GoldInfo, has_all_obj),
    offsetof(ShuffleInfo__Metadata__GoldInfo, all_obj),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "norand_obj",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(ShuffleInfo__Metadata__GoldInfo, has_norand_obj),
    offsetof(ShuffleInfo__Metadata__GoldInfo, norand_obj),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "static_got",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(ShuffleInfo__Metadata__GoldInfo, has_static_got),
    offsetof(ShuffleInfo__Metadata__GoldInfo, static_got),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "silicon_errata",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(ShuffleInfo__Metadata__GoldInfo, has_silicon_errata),
    offsetof(ShuffleInfo__Metadata__GoldInfo, silicon_errata),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tls_opt",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(ShuffleInfo__Metadata__GoldInfo, has_tls_opt),
    offsetof(ShuffleInfo__Metadata__GoldInfo, tls_opt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "got_opt",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(ShuffleInfo__Metadata__GoldInfo, has_got_opt),
    offsetof(ShuffleInfo__Metadata__GoldInfo, got_opt),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "got_target",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(ShuffleInfo__Metadata__GoldInfo, has_got_target),
    offsetof(ShuffleInfo__Metadata__GoldInfo, got_target),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tls_got_target",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(ShuffleInfo__Metadata__GoldInfo, has_tls_got_target),
    offsetof(ShuffleInfo__Metadata__GoldInfo, tls_got_target),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "plt_target",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(ShuffleInfo__Metadata__GoldInfo, has_plt_target),
    offsetof(ShuffleInfo__Metadata__GoldInfo, plt_target),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "merged_target",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(ShuffleInfo__Metadata__GoldInfo, has_merged_target),
    offsetof(ShuffleInfo__Metadata__GoldInfo, merged_target),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ifunc_target",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(ShuffleInfo__Metadata__GoldInfo, has_ifunc_target),
    offsetof(ShuffleInfo__Metadata__GoldInfo, ifunc_target),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "missrandfile",
    12,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(ShuffleInfo__Metadata__GoldInfo, n_missrandfile),
    offsetof(ShuffleInfo__Metadata__GoldInfo, missrandfile),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "c_fun",
    13,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(ShuffleInfo__Metadata__GoldInfo, has_c_fun),
    offsetof(ShuffleInfo__Metadata__GoldInfo, c_fun),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned shuffle_info__metadata__gold_info__field_indices_by_name[] = {
  0,   /* field[0] = all_obj */
  12,   /* field[12] = c_fun */
  5,   /* field[5] = got_opt */
  6,   /* field[6] = got_target */
  10,   /* field[10] = ifunc_target */
  9,   /* field[9] = merged_target */
  11,   /* field[11] = missrandfile */
  1,   /* field[1] = norand_obj */
  8,   /* field[8] = plt_target */
  3,   /* field[3] = silicon_errata */
  2,   /* field[2] = static_got */
  7,   /* field[7] = tls_got_target */
  4,   /* field[4] = tls_opt */
};
static const ProtobufCIntRange shuffle_info__metadata__gold_info__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 13 }
};
const ProtobufCMessageDescriptor shuffle_info__metadata__gold_info__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ShuffleInfo.Metadata.GoldInfo",
  "GoldInfo",
  "ShuffleInfo__Metadata__GoldInfo",
  "ShuffleInfo",
  sizeof(ShuffleInfo__Metadata__GoldInfo),
  13,
  shuffle_info__metadata__gold_info__field_descriptors,
  shuffle_info__metadata__gold_info__field_indices_by_name,
  1,  shuffle_info__metadata__gold_info__number_ranges,
  (ProtobufCMessageInit) shuffle_info__metadata__gold_info__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor shuffle_info__metadata__field_descriptors[4] =
{
  {
    "funs",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ShuffleInfo__Metadata, n_funs),
    offsetof(ShuffleInfo__Metadata, funs),
    &shuffle_info__metadata__fun_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fixups",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ShuffleInfo__Metadata, n_fixups),
    offsetof(ShuffleInfo__Metadata, fixups),
    &shuffle_info__metadata__fixup_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "otherfixups",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ShuffleInfo__Metadata, n_otherfixups),
    offsetof(ShuffleInfo__Metadata, otherfixups),
    &shuffle_info__metadata__fixup_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "goldinfo",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(ShuffleInfo__Metadata, goldinfo),
    &shuffle_info__metadata__gold_info__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned shuffle_info__metadata__field_indices_by_name[] = {
  1,   /* field[1] = fixups */
  0,   /* field[0] = funs */
  3,   /* field[3] = goldinfo */
  2,   /* field[2] = otherfixups */
};
static const ProtobufCIntRange shuffle_info__metadata__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor shuffle_info__metadata__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ShuffleInfo.Metadata",
  "Metadata",
  "ShuffleInfo__Metadata",
  "ShuffleInfo",
  sizeof(ShuffleInfo__Metadata),
  4,
  shuffle_info__metadata__field_descriptors,
  shuffle_info__metadata__field_indices_by_name,
  1,  shuffle_info__metadata__number_ranges,
  (ProtobufCMessageInit) shuffle_info__metadata__init,
  NULL,NULL,NULL    /* reserved[123] */
};
